import { Titular } from './titulares';

export const TITULARES: Titular[] = [
  {
    id: 1,
    name: 'Carlos Barrocas',
    alcoholismo: 99,
    dinero: 50,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'Si',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 2,
    name: 'Anxo Alcalde',
    alcoholismo: 99,
    dinero: 89,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'Si',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 3,
    name: 'Cañe (Produccion)',
    alcoholismo: 99,
    dinero: 79,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 3,
    name: 'Guldris',
    alcoholismo: 60,
    dinero: 99,
    aguante: 60,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 4,
    name: 'Efren',
    alcoholismo: 99,
    dinero: 50,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 5,
    name: 'Brais Meco',
    alcoholismo: 70,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'Si',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 6,
    name: 'Alex (Barto)',
    alcoholismo: 50,
    dinero: 99,
    aguante: 70,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 7,
    name: 'Izan',
    alcoholismo: 99,
    dinero: 80,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 8,
    name: 'Carmen Varela',
    alcoholismo: 99,
    dinero: 79,
    aguante: 89,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 9,
    name: 'Pablo Sixto (Pistolero)',
    alcoholismo: 99,
    dinero: 79,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 10,
    name: 'Ana Quiroga',
    alcoholismo: 80,
    dinero: 80,
    aguante: 80,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
];
