import { Jugador } from './jugadores';

export const JUGADORES: Jugador[] = [
  {
    id: 1,
    name: 'Carlos Barrocas',
    alcoholismo: 99,
    dinero: 50,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'Si',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 2,
    name: 'Anxo Alcalde',
    alcoholismo: 99,
    dinero: 89,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'Si',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 3,
    name: 'Cañe (Produccion)',
    alcoholismo: 99,
    dinero: 79,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 3,
    name: 'Guldris',
    alcoholismo: 60,
    dinero: 99,
    aguante: 60,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 4,
    name: 'Efren',
    alcoholismo: 99,
    dinero: 50,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 5,
    name: 'Brais Meco',
    alcoholismo: 70,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'Si',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 6,
    name: 'Alex (Barto)',
    alcoholismo: 50,
    dinero: 99,
    aguante: 70,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 7,
    name: 'Izan',
    alcoholismo: 99,
    dinero: 80,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 8,
    name: 'Carmen Varela',
    alcoholismo: 99,
    dinero: 79,
    aguante: 89,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 9,
    name: 'Pablo Sixto (Pistolero)',
    alcoholismo: 99,
    dinero: 79,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 10,
    name: 'Ana Quiroga',
    alcoholismo: 80,
    dinero: 80,
    aguante: 80,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },

  {
    id: 11,
    name: 'Real Happy Men',
    alcoholismo: 30,
    dinero: 30,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 12,
    name: 'Nervios (Legionario)',
    alcoholismo: 99,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'Si',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 13,
    name: 'Cuxi',
    alcoholismo: 99,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'Si',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 13,
    name: 'Pepin',
    alcoholismo: 60,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Bebidas Caseras', // Incluye la opción de bebida aquí
  },
  {
    id: 14,
    name: 'Chemita',
    alcoholismo: 70,
    dinero: 99,
    aguante: 60,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 15,
    name: 'Borjon',
    alcoholismo: 70,
    dinero: 99,
    aguante: 70,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 16,
    name: 'Miguelon',
    alcoholismo: 50,
    dinero: 99,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 17,
    name: 'Caxo',
    alcoholismo: 79,
    dinero: 99,
    aguante: 89,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ginebra', // Incluye la opción de bebida aquí
  },
  {
    id: 18,
    name: 'Edu',
    alcoholismo: 79,
    dinero: 99,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ginebra', // Incluye la opción de bebida aquí
  },
  {
    id: 19,
    name: 'Ruby',
    alcoholismo: 89,
    dinero: 99,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Bacardi Limon', // Incluye la opción de bebida aquí
  },
  {
    id: 20,
    name: 'Dani Barrocas',
    alcoholismo: 99,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'Si',
    bebida: 99,
    opcionBebida: 'Ginebra', // Incluye la opción de bebida aquí
  },
  {
    id: 22,
    name: 'Cucca',
    alcoholismo: 79,
    dinero: 79,
    aguante: 69,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 23,
    name: 'Aitana',
    alcoholismo: 69,
    dinero: 59,
    aguante: 89,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
];
