import { Suplente } from './suplentes';

export const SUPLENTES: Suplente[] = [
  {
    id: 11,
    name: 'Real Happy Men',
    alcoholismo: 30,
    dinero: 30,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 12,
    name: 'Nervios (Legionario)',
    alcoholismo: 99,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'Si',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 13,
    name: 'Cuxi',
    alcoholismo: 99,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'Si',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 13,
    name: 'Pepin',
    alcoholismo: 60,
    dinero: 99,
    aguante: 99,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Bebidas Caseras', // Incluye la opción de bebida aquí
  },
  {
    id: 14,
    name: 'Chemita',
    alcoholismo: 70,
    dinero: 99,
    aguante: 60,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 15,
    name: 'Borjon',
    alcoholismo: 70,
    dinero: 99,
    aguante: 70,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Whisky', // Incluye la opción de bebida aquí
  },
  {
    id: 16,
    name: 'Miguelon',
    alcoholismo: 50,
    dinero: 99,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ron', // Incluye la opción de bebida aquí
  },
  {
    id: 17,
    name: 'Caxo',
    alcoholismo: 79,
    dinero: 99,
    aguante: 89,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ginebra', // Incluye la opción de bebida aquí
  },
  {
    id: 18,
    name: 'Edu',
    alcoholismo: 79,
    dinero: 99,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Ginebra', // Incluye la opción de bebida aquí
  },
  {
    id: 19,
    name: 'Ruby',
    alcoholismo: 89,
    dinero: 99,
    aguante: 79,
    trucos: 1,
    opcionTrucos: 'No',
    tubo: 99,
    opcionTubo: 'No',
    bebida: 99,
    opcionBebida: 'Bacardi Limon', // Incluye la opción de bebida aquí
  },
];
